// Run this once to seed your DB: node src/modules/learning/seed.js
import mongoose from "mongoose";
import { LearningModule } from "./learning.model.js";
import "../../config/env.js";
import { connectDB } from "../../config/db.js";

const modules = [
  {
    title: "Money Basics",
    description: "Understanding money, inflation, and financial fundamentals",
    icon: "💵",
    difficulty: "Beginner",
    xpReward: 200,
    order: 1,
    lessons: [
      { order: 1, title: "What is Money?", duration: 5, content: "Money is anything that people generally accept as a medium of exchange for goods and services. Instead of bartering (exchanging one product directly for another), money allows people to buy and sell easily. It can take different forms such as coins, paper notes, or digital money in bank accounts. Money is issued and regulated by governments or financial authorities and is widely trusted by people for transactions. Money performs several important functions in an economy. It acts as a medium of exchange, making trade easier between buyers and sellers. It also works as a unit of account, meaning it provides a common measure to determine the value of goods and services. Additionally, money serves as a store of value, allowing people to save purchasing power and use it in the future. In modern economies, money also helps in economic growth and financial stability. It facilitates payments, investments, and savings, which are essential for businesses and individuals. With the advancement of technology, money is increasingly used in digital forms such as online banking, mobile payments, and electronic transfers, making transactions faster and more convenient." },
      { order: 2, title: "Understanding Inflation", duration: 6, content: "Inflation refers to the increase in the general prices of goods and services over time, which reduces the purchasing power of money. When inflation rises, the same amount of money buys fewer goods and services than before. For example, if a product costs ₹100 today and inflation increases, it might cost ₹110 in the future. Inflation affects everyday expenses, savings, and investments, making it important for individuals to plan their finances wisely to maintain their purchasing power." },
      { order: 3, title: "Time Value of Money", duration: 7, content: "The time value of money means that money available today is worth more than the same amount in the future because it can be invested and earn interest. For example, ₹1,000 today can be invested to grow over time, making it more valuable than receiving ₹1,000 several years later. This concept is important in financial planning, saving, and investing because it helps people understand the benefits of investing early and allowing their money to grow over time." },
      { order: 4, title: "Income vs Wealth", duration: 5, content: "Income refers to the money a person earns regularly through sources such as salary, business profits, or investments. Wealth, on the other hand, refers to the total value of assets a person owns, such as property, savings, investments, and other valuable possessions. While income shows how much money a person earns, wealth represents the financial resources accumulated over time. Managing income wisely and investing it properly can help individuals build wealth for long-term financial security." },
      { order: 5, title: "Financial Goals", duration: 5, content: "Financial goals are the targets or objectives that people set to manage their money and achieve financial stability. These goals can be short-term, such as saving for a phone or vacation, or long-term, such as buying a house, funding education, or planning for retirement. Setting clear financial goals helps individuals plan their spending, saving, and investing decisions more effectively. It also encourages discipline and helps people stay focused on their future financial needs." },
      { order: 6, title: "Banking Basics", duration: 6, content: "Banking basics involve understanding how banks help people manage and store their money safely. Banks provide services such as savings accounts, current accounts, loans, and money transfers. People deposit their money in banks for security and convenience, and banks may also provide interest on savings. Banking systems also make transactions easier through services like debit cards, online banking, and mobile banking, allowing individuals to access and manage their funds efficiently." },
      { order: 7, title: "Taxes in India", duration: 8, content: "Taxes in India are compulsory payments made by individuals and businesses to the government to fund public services and development activities. The government uses tax revenue for infrastructure, education, healthcare, and defense. There are different types of taxes, such as income tax, Goods and Services Tax (GST), and corporate tax. Paying taxes is a legal responsibility, and understanding the tax system helps individuals manage their finances and comply with government regulations." },
      { order: 8, title: "Financial Safety Net", duration: 5, content: "A financial safety net refers to the savings or resources set aside to handle unexpected financial emergencies. This may include emergency funds, insurance policies, or other financial support systems that help individuals manage sudden expenses such as medical emergencies, job loss, or accidents. Having a financial safety net provides security and peace of mind, ensuring that unexpected situations do not cause serious financial problems." },
    ],
    quiz: [
      { question: "What is the primary function of money?", options: ["Store of value", "Medium of exchange", "Unit of account", "All of the above"], correctIndex: 3, explanation: "Money serves all three functions — exchange, value storage, and unit of account." },
      { question: "If inflation is 6% and your savings earn 4%, what is your real return?", options: ["+10%", "+2%", "-2%", "0%"], correctIndex: 2, explanation: "Real return = nominal return - inflation = 4% - 6% = -2%. You're losing purchasing power!" },
      { question: "Which Section of Indian Income Tax allows deduction for PPF investments?", options: ["80D", "80C", "80G", "10(10D)"], correctIndex: 1, explanation: "Section 80C allows deductions up to ₹1.5 lakh for PPF, ELSS, LIC, home loan principal, etc." },
      { question: "What should an emergency fund cover?", options: ["1 month expenses", "3-6 months expenses", "1 year expenses", "Only rent"], correctIndex: 1, explanation: "3-6 months of expenses is the standard recommendation. It covers job loss, medical emergencies, or unexpected repairs." },
    ],
  },
  {
    title: "Smart Budgeting",
    description: "Create and manage budgets, track expenses, and build savings",
    icon: "📊",
    difficulty: "Beginner",
    xpReward: 250,
    order: 2,
    lessons: [
      { order: 1, title: "The 50/30/20 Rule", duration: 6, content: "The 50/30/20 rule is a simple budgeting method that helps people manage their income effectively. According to this rule, 50% of income should be spent on necessities such as rent, food, and bills, 30% can be used for wants like entertainment or shopping, and the remaining 20% should be saved or invested. This method helps individuals maintain a balance between spending and saving while ensuring that essential needs are covered. It is widely used because it provides a clear and easy way to organize personal finances." },
      { order: 2, title: "Tracking Your Expenses", duration: 7, content: "Tracking your expenses means keeping a record of all the money you spend daily, weekly, or monthly. By noting where your money goes, you can better understand your spending habits and identify areas where you may be overspending. This can be done using notebooks, spreadsheets, or mobile apps designed for budgeting. Regularly tracking expenses helps people stay within their budget and make smarter financial decisions." },
      { order: 3, title: "Zero-Based Budgeting", duration: 6, content: "Zero-based budgeting is a budgeting method where every rupee of income is assigned a specific purpose. At the end of the budgeting process, income minus expenses equals zero, meaning all money is planned for either spending, saving, or investing. This approach encourages careful planning and ensures that money is not wasted. It also helps individuals prioritize their financial goals and maintain better control over their finances." },
      { order: 4, title: "Cutting Unnecessary Expenses", duration: 5, content: "Cutting unnecessary expenses involves identifying and reducing spending on items or services that are not essential. This may include reducing frequent dining out, cancelling unused subscriptions, or avoiding impulse purchases. By controlling these expenses, individuals can free up more money for savings, investments, or important financial goals. Developing mindful spending habits can significantly improve financial stability over time." },
      { order: 5, title: "Building Your Savings Rate", duration: 7, content: "Building your savings rate means increasing the percentage of your income that you save regularly. A higher savings rate helps individuals prepare for future needs, emergencies, and long-term goals such as buying a house or retirement planning. This can be achieved by reducing unnecessary expenses, increasing income, or automatically transferring a portion of income to savings accounts. Consistent saving habits help build financial security over time." },
      { order: 6, title: "Sinking Funds", duration: 5, content: "Sinking funds are savings set aside for specific future expenses that are expected but not monthly. Examples include saving for car repairs, vacations, festivals, or insurance payments. Instead of paying a large amount at once, people gradually save small amounts over time. This helps avoid financial stress and prevents the need to take loans or use credit for planned expenses." },
      { order: 7, title: "Dealing with Debt", duration: 8, content: "Dealing with debt involves managing and repaying borrowed money in a responsible way. People may have debts such as credit card balances, personal loans, or education loans. Effective debt management includes creating a repayment plan, paying bills on time, and avoiding unnecessary borrowing. By reducing debt gradually and maintaining good financial discipline, individuals can improve their financial health." },
      { order: 8, title: "Budget Review & Adjustment", duration: 5, content: "Budget review and adjustment means regularly checking your budget to see if it still matches your income, expenses, and financial goals. As life situations change, such as changes in income or new expenses, the budget may need to be modified. Reviewing the budget helps identify problems early and allows people to make better financial decisions. This practice ensures that the budget remains practical and effective over time." },
      { order: 9, title: "Budgeting for Irregular Income", duration: 6, content: "Budgeting for irregular income is important for people whose earnings change from month to month, such as freelancers, commission-based workers, or business owners. Instead of relying on a fixed monthly income, individuals plan their expenses based on their lowest expected income. Saving extra money during higher-earning months can help cover expenses during lower-income periods. This approach provides financial stability even when income fluctuates." },
      { order: 10, title: "Family Budgeting", duration: 6, content: "Family budgeting involves planning and managing the income and expenses of an entire household. It includes allocating money for essential needs such as housing, food, education, and healthcare while also planning for savings and emergencies. Family members often discuss and agree on financial priorities to ensure responsible spending. A well-planned family budget helps maintain financial balance and supports long-term financial security for everyone in the household." },
    ],
    quiz: [
      { question: "In the 50/30/20 rule, what does the 20% represent?", options: ["Food and transport", "Entertainment", "Savings and debt repayment", "Housing"], correctIndex: 2, explanation: "20% goes toward savings and paying off debt — building your financial future." },
      { question: "What is zero-based budgeting?", options: ["Having zero savings", "Every rupee is assigned a purpose so income minus expenses = 0", "Spending nothing", "Budgeting only for zero-interest items"], correctIndex: 1, explanation: "Zero-based budgeting means every rupee of income is allocated — to expenses, savings, or investments." },
      { question: "What is a sinking fund?", options: ["A fund that loses money", "Money saved monthly for a known future expense", "A type of mutual fund", "Emergency fund"], correctIndex: 1, explanation: "A sinking fund smooths out large, predictable future expenses by saving a little each month." },
      { question: "Which debt repayment strategy is mathematically optimal?", options: ["Snowball method", "Avalanche method", "Minimum payment only", "Consolidation always"], correctIndex: 1, explanation: "Avalanche (highest interest first) saves the most money in interest payments over time." },
    ],
  },
  {
    title: "Investment Fundamentals",
    description: "Stocks, mutual funds, SIPs, and portfolio building",
    icon: "📈",
    difficulty: "Intermediate",
    xpReward: 300,
    order: 3,
    lessons: [
      { order: 1, title: "Why Invest?", duration: 5, content: "Investing means putting money into financial assets with the aim of earning returns over time. Instead of letting money remain idle, investing allows it to grow through interest, dividends, or capital appreciation. It helps individuals build wealth, beat inflation, and achieve long-term financial goals such as buying a house, funding education, or retirement planning. Investing wisely over time can significantly increase financial security." },
      { order: 2, title: "Risk and Return", duration: 7, content: "Risk and return are closely related concepts in investing. Risk refers to the possibility of losing money or not getting the expected return on an investment. Return refers to the profit or income earned from an investment over time. Generally, investments with higher potential returns carry higher risks, while safer investments usually offer lower returns. Understanding this balance helps investors choose investments that match their financial goals and risk tolerance." },
      { order: 3, title: "Stock Market Basics", duration: 8, content: "The stock market is a platform where investors buy and sell shares of publicly listed companies. When a person buys a share, they become a partial owner of that company and may benefit if the company's value increases. Stock prices change based on factors such as company performance, economic conditions, and investor demand. The stock market helps companies raise capital and gives investors an opportunity to grow their money." },
      { order: 4, title: "Mutual Funds Explained", duration: 8, content: "A mutual fund is an investment option where money from many investors is pooled together and managed by professional fund managers. The collected money is invested in various assets such as stocks, bonds, or other securities. This allows individuals to invest in a diversified portfolio even with a small amount of money. Mutual funds are popular because they provide professional management and reduce the need for individual investors to select investments themselves." },
      { order: 5, title: "Power of SIP", duration: 7, content: "A Systematic Investment Plan (SIP) is a method of investing a fixed amount of money regularly, usually every month, into mutual funds. SIP helps investors build wealth gradually by investing small amounts consistently instead of a large amount at once. It also benefits from rupee cost averaging, where investors buy more units when prices are low and fewer units when prices are high. Over time, this disciplined and regular investment approach can lead to significant wealth creation, making SIP a popular choice for long-term financial planning." },
      { order: 6, title: "Compounding — The 8th Wonder", duration: 6, content: "Compounding refers to the process where the returns earned on an investment start generating their own returns over time. In simple terms, you earn interest not only on the original investment but also on the interest already earned. Because of this effect, investments can grow much faster over long periods. This powerful growth effect is why compounding is often called the “8th wonder of the world,” highlighting how consistent investing and patience can turn small investments into large amounts in the future." },
      { order: 7, title: "Diversification", duration: 6, content: "Diversification is the practice of spreading investments across different assets or sectors to reduce risk. Instead of investing all money in a single stock or asset, investors allocate funds to multiple investments such as stocks, bonds, or mutual funds. If one investment performs poorly, others may perform better and balance the overall risk. Diversification helps create a more stable and balanced investment portfolio." },
      { order: 8, title: "Index Funds vs Active Funds", duration: 7, content: "Index funds and active funds are two types of mutual funds with different management styles. Index funds aim to replicate the performance of a market index, such as the Nifty 50 or Sensex, by investing in the same companies included in that index. Active funds, on the other hand, are managed by fund managers who actively select stocks to try to outperform the market. Index funds generally have lower fees, while active funds aim for potentially higher returns through active management." },
      { order: 9, title: "PPF and Tax-Saving Investments", duration: 7, content: "The Public Provident Fund (PPF) is a popular long-term savings scheme in India backed by the government. It offers a fixed interest rate and provides tax benefits under Section 80C of the Income Tax Act. Investments in PPF are safe and have a long maturity period, usually 15 years. Many people use PPF as a tax-saving and retirement planning tool because of its stability and tax advantages." },
      { order: 10, title: "Building Your First Portfolio", duration: 8, content: "Building your first investment portfolio involves selecting a mix of different investments based on your financial goals, time horizon, and risk tolerance. Beginners often start with a combination of stocks, mutual funds, and safe investments such as government-backed schemes. A balanced portfolio helps manage risk while allowing investments to grow over time. Regular investing and reviewing the portfolio can help individuals stay aligned with their financial objectives." },
      { order: 11, title: "Common Investment Mistakes", duration: 6, content: "Many investors make mistakes such as investing without proper research, following market trends blindly, or reacting emotionally to short-term market changes. Other common errors include lack of diversification, trying to time the market, and investing without clear financial goals. These mistakes can reduce potential returns and increase risk. Learning about investments and maintaining discipline can help avoid such errors." },
      { order: 12, title: "Tracking Your Investments", duration: 5, content: "Tracking your investments means regularly monitoring the performance of your investment portfolio. This helps investors understand whether their investments are meeting their financial goals or need adjustments. People can track investments through financial apps, brokerage platforms, or personal records. Regular tracking ensures that investors stay informed about market changes and make better decisions regarding their financial future." },
    ],
    quiz: [
      { question: "What is rupee cost averaging in SIP?", options: ["Paying a fixed price always", "Buying more units when prices are low and fewer when high", "Averaging your loan costs", "Splitting investments across currencies"], correctIndex: 1, explanation: "SIP automatically buys more units when prices are low and fewer when high, reducing average cost over time." },
      { question: "Which type of mutual fund has the lowest expense ratio?", options: ["Active large-cap fund", "Sectoral fund", "Index fund", "ELSS fund"], correctIndex: 2, explanation: "Index funds passively track an index with minimal management, so expense ratios are very low (~0.1%)." },
      { question: "Under which section can you claim NPS additional deduction?", options: ["80C", "80D", "80CCD(1B)", "80G"], correctIndex: 2, explanation: "Section 80CCD(1B) allows an additional ₹50,000 deduction for NPS contributions, over and above the 80C limit." },
      { question: "₹1 lakh invested at 12% for 30 years approximately becomes?", options: ["₹5 lakhs", "₹15 lakhs", "₹30 lakhs", "₹1 crore"], correctIndex: 2, explanation: "At 12% compounded annually for 30 years: ₹1L × (1.12)^30 ≈ ₹30 lakhs. That's the power of compounding!" },
    ],
  },
  {
    title: "Credit & Loans",
    description: "Credit scores, loan types, EMI calculations, and debt management",
    icon: "💳",
    difficulty: "Intermediate",
    xpReward: 275,
    order: 4,
    lessons: [
      { order: 1, title: "What is Credit?", duration: 5, content: "Credit refers to the ability to borrow money or access goods and services with the promise to pay for them later. It allows individuals to make purchases or cover expenses even when they do not have enough cash at the moment. Credit is usually provided by banks, financial institutions, or lenders in the form of loans, credit cards, or credit lines. Borrowers are expected to repay the borrowed amount within a specific time along with interest." },
      { order: 2, title: "Credit Score Explained", duration: 7, content: "A credit score is a numerical representation of a person’s creditworthiness based on their past borrowing and repayment behavior. In India, credit scores generally range from 300 to 900, with a higher score indicating better financial reliability. Lenders use this score to decide whether to approve a loan or credit card application. Factors such as timely loan payments, credit usage, and repayment history influence a person’s credit score." },
      { order: 3, title: "How to Build Credit", duration: 6, content: "Building credit involves developing a good borrowing and repayment history over time. This can be done by using credit responsibly, such as paying credit card bills on time, taking small loans and repaying them regularly, and maintaining a low credit utilization ratio. Avoiding missed payments and keeping long-standing credit accounts also helps improve credit history. A strong credit profile increases the chances of getting loans with better interest rates." },
      { order: 4, title: "Understanding EMI", duration: 7, content: "EMI stands for Equated Monthly Installment, which is the fixed amount a borrower pays every month to repay a loan. An EMI usually includes both the principal amount borrowed and the interest charged by the lender. The EMI amount depends on factors such as the loan amount, interest rate, and loan tenure. Paying EMIs regularly helps borrowers repay loans gradually without having to pay the entire amount at once." },
      { order: 5, title: "Home Loans", duration: 8, content: "A home loan is a type of long-term loan provided by banks or financial institutions to help individuals purchase or construct a house. The borrower repays the loan in monthly installments over several years, usually ranging from 10 to 30 years. Home loans generally have lower interest rates compared to other loans because they are secured against the property being purchased. They also offer certain tax benefits under Indian tax laws." },
      { order: 6, title: "Personal Loans vs Credit Cards", duration: 6, content: "Personal loans and credit cards are both forms of borrowing but serve different purposes. A personal loan provides a lump sum amount that must be repaid in fixed EMIs over a specific period. Credit cards, on the other hand, allow users to borrow money up to a certain limit and repay it later, usually with interest if the full balance is not paid on time. Personal loans typically have lower interest rates than credit cards, which often carry higher interest charges." },
      { order: 7, title: "Student Loans in India", duration: 6, content: "Student loans in India are designed to help students finance their higher education, including tuition fees, accommodation, and other academic expenses. These loans are usually provided by banks with relatively lower interest rates and flexible repayment options. In many cases, repayment begins after the student completes their education and finds employment. Student loans make higher education more accessible to individuals who may not have sufficient financial resources." },
      { order: 8, title: "Avoiding Debt Traps", duration: 6, content: "A debt trap occurs when a person continues borrowing money to repay existing debts, leading to a cycle of increasing financial burden. This situation often happens when people take high-interest loans or rely heavily on credit cards without proper repayment planning. To avoid debt traps, individuals should borrow responsibly, maintain a budget, and ensure they can comfortably repay loans before borrowing. Proper financial planning and disciplined spending help prevent such situations." },
      { order: 9, title: "Loan Against Securities", duration: 5, content: "A loan against securities is a type of secured loan where individuals borrow money by pledging their financial assets such as shares, mutual funds, bonds, or insurance policies as collateral. The lender provides a loan based on the value of these securities while the borrower continues to own the investments. This type of loan usually has lower interest rates compared to unsecured loans because it is backed by assets. It is often used to meet short-term financial needs without selling investments." },
    ],
    quiz: [
      { question: "What CIBIL score is considered excellent in India?", options: ["Above 650", "Above 700", "Above 750", "Above 800"], correctIndex: 2, explanation: "750+ is generally considered excellent and qualifies you for the best loan rates." },
      { question: "What is the credit utilization ratio you should stay below?", options: ["10%", "30%", "50%", "75%"], correctIndex: 1, explanation: "Keep credit utilization below 30% of your total credit limit for a healthy credit score." },
      { question: "Which section allows deduction on education loan interest?", options: ["80C", "80D", "80E", "24b"], correctIndex: 2, explanation: "Section 80E allows deduction of interest paid on education loans for up to 8 years with no upper limit." },
      { question: "What does FOIR stand for and what is a safe range?", options: ["Fixed Outgo Income Ratio, below 20%", "Fixed Obligations to Income Ratio, below 40-50%", "Financial Output Interest Rate, below 10%", "Fund Offset Interest Ratio, below 60%"], correctIndex: 1, explanation: "FOIR = total EMIs / monthly income. Keeping it below 40-50% ensures you have enough for living expenses and savings." },
    ],
  },
];

const seed = async () => {
  await connectDB();
  await LearningModule.deleteMany({});
  await LearningModule.insertMany(modules);
  console.log(`✅ Seeded ${modules.length} learning modules successfully!`);
  process.exit(0);
};

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});